services:
  - type: web
    name: blasm-landing
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    autoDeploy: true
    repo: https://github.com/VltrnOne/blasm-landing
    branch: main
